kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql
  namespace: jira-test
data:
  my.cnf: |-
    [client]
    port            = 3306
    default-character-set=utf8
    socket          = /var/run/mysqld/mysqld.sock
 
    [mysql]
    default-character-set=utf8
 
    [mysqld_safe]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    nice            = 0
 
    [mysqld]
    skip-host-cache
    skip-name-resolve
    user            = mysql
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    port            = 3306
    basedir         = /usr
    datadir         = /var/lib/mysql
    tmpdir          = /tmp
    lc-messages-dir = /usr/share/mysql
    explicit_defaults_for_timestamp
    character-set-server=utf8
    default-storage-engine=INNODB
    max_allowed_packet=256M
    innodb_log_file_size=256M
 
 
    sql_mode = NO_AUTO_VALUE_ON_ZERO
 
 
    symbolic-links=0
 
    [mysqld.safe]
    default-character-set=utf8
    [mysql.server]
    default-character-set=utf8
 
    #
    !includedir /etc/mysql/conf.d/
