---

- name: Add yum repository
  yum_repository:
    name: kubernetes
    description: kubernetes YUM repo
    baseurl: https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
    gpgkey: 
      - https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg 
      - https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
    gpgcheck: yes

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: 
      - http://mirrors.aliyun.com/epel/7/$basearch
      - http://mirrors.aliyun.com/epel/7/$basearch/debug
      - http://mirrors.aliyun.com/epel/7/SRPMS
    gpgcheck: no

- name: Install kubernetes tools
  yum:
    name: ["kubelet-1.16.9", "kubectl-1.16.9", "kubeadm-1.16.9", kubernetes-cni]
    disable_excludes: kubernetes
    state: present


- name: Enable kubelet service
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Reboot
  reboot:
    reboot_timeout: 180