#!/bin/sh
output=`date  |awk  '{print $3"-"$2"-"$NF}'`
name=`curl  http://package.alauda.cn:12345/IDC/ |grep online|grep  $output|sort -k2 -r |awk -F '<|>' '{print $3}'|head -1|awk -F "-" '{print $2"-"$3}'`
mv output.xls $name.xls
#rm -rf f1 f2 f3  data.txt  install*
