---
  - name: Copy backup script
    ansible.builtin.copy:
      src: ./files/etcd_backup.sh
      dest: /usr/local/scripts/upgrade/backup_etcd.sh
      owner: root
      group: root
      mode: '0644'

  - name: Create cronjob to backup etcd
    ansible.builtin.cron:
      name: "etcd backup"
      minute: "0"
      hour: "0"
      job: "/usr/local/scripts/upgrade/backup_etcd.sh"