---
# setup system

# 关闭 swap
- name: Disabling Swap on all nodes
  shell: swapoff -a

# 关闭 自动挂载
- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

#关闭防火墙
- name: Disable firewall
  systemd:
    name: firewalld
    state: stopped

# Letting iptables see bridged traffic
- name: Ensure br_netfilter is enabled.
  modprobe:
    name: br_netfilter
    state: present

- name: Set system ip6tables config
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
    reload: yes

- name: Set system swap config
  sysctl:
    name: vm.swappiness
    value: '0'
    state: present
    reload: yes

- name: Set system iptables config
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    reload: yes

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
